### ISSUE TITLE
Unable to install package

### ISSUE THREAD

**Issue by mocalvao** [rstudio/EDAWR#3]
Hi there,

I have issued the command:

devtools::install_github("rstudio/EDAWR")

from within RStudio's console and the following message was written:

Downloading GitHub repo rstudio/EDAWR@master
from URL https://api.github.com/repos/rstudio/EDAWR/zipball/master
Installing EDAWR
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0  0     0    0     0    0     0      0      0 --:--:--  0:00:01 --:--:--     0
curl: (22) The requested URL returned error: 404
Warning in download.packages(x$name, destdir = dest_dir, repos = x$repos,  :
  download of package ‘babynames’ failed
Error in download.packages(x$name, destdir = dest_dir, repos = x$repos,  : 
  subscript out of bounds
In addition: Warning message:
In download.file(url, destfile, method, mode = "wb", ...) :
  download had nonzero exit status

Could you give me any clue to solve the problem?

**Comment by garrettgman** [comment]
@mocalvao The command is working for me. The best advice would be to check that you have the latest versions of R and devtools, then retry.
